---
abstract: Create a graph from a MojoX::Routes object
author: Pedro Melo <melo@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.091290
license: perl
name: MojoX-Routes-AsGraph
requires:
  Graph::Easy: '0'
  Mojo: '0'
  Test::More: '0'
resources:
  repository: http://github.com/melo/mojox-routes-asgraph/
version: '0.04'
